### PR TITLE
Idn support

### PR DESCRIPTION
**Pull request by baudehlo**
Should facilitate SMTPUTF8 support in Haraka

### CODE REVIEW

**Comment by msimerson** [comment]
### TODO

- [ ] add punycode as package dependency
- [ ] bump version in package.json
- [ ] update Changes.md
- [ ] publish to npm

**Comment by baudehlo** [comment]
FWIW punycode is core node.js

**Comment by msimerson** [comment]
> FWIW punycode is core node.js

So because some other package depends on this one that also requires punycode, this one shouldn't have to adhere to npm module customs and declare its own dependency on it?

**Comment by msimerson** [comment]
[https://nodejs.org/api/punycode.html](https://nodejs.org/api/punycode.html)

"The version of the punycode module bundled in Node.js is being deprecated. In a future major version of Node.js this module will be removed. Users currently depending on the punycode module should switch to using the userland-provided Punycode.js module instead."

(We already explicitly depend on the npm packaged version of punycode in haraka-tld).

**Comment by baudehlo** [comment]
Didn't know that. Fair enough.

But for your other comment, we don't list a dependency on "fs" for example.

**Comment by msimerson** [comment]
> But for your other comment, we don't list a dependency on "fs" for example.

I had misread "core node.js" as "core" and initially thought you meant Haraka's core.

**Comment by baudehlo** [comment]
Yeah no biggie. I will fix when I get off my ass onto a real computer. :)

**Comment by baudehlo** [comment]
What typo?

**Comment by msimerson** [comment]
To find the typo, search for `adress`

**Comment by andris9** [comment]
Regarding punycode, I included punycode.js in Nodemailer for a while but stopped doing that pretty fast and kept using the deprecated native module:

1. If you use the latest stable of punycode.js then it is going to start showing warnings on older versions of Node (including v4) because punycode.js requires at least Node v6
2. Whichever version of punycode.js you are using, Node is not going to use it. If there are multiple modules with the same name, then Node prefers the built-in one and there already is a module named punycode

So what happened in my case was that people started to complain about the warnings when installing Nodemailer even though the module that caused the warnings wasn't actually even used.

Regarding RFC6531, do you intend to use the SMTPUTF8 keyword for MAIL FROM somehow or do you just silently ignore it? If it is just ignored then I guess it doesn't really matter though.

**Comment by baudehlo** [comment]
We'll just ignore the keyword.

@msimerson what do you think about the npm module issue?

**Comment by msimerson** [comment]
> what do you think about the npm module issue?

Punycode was deprecated in v7 and is expected to be removed in node v8. I'd much rather add the explicit dependency and so we're future-ready than worry about users of node v4 getting a module warning. Users getting this newer version of Haraka and module will be mostly new installs and most distros are already bundling node v6 or v7.  I suspect warnings on node v4 will be few and will tail off to zero over the next 10 months when node v4 is EOL.

**Comment by baudehlo** [comment]
OK. This should be ready to merge and release now.

**Comment by msimerson** [comment]
Also, there's a conversation regarding punycode over at [https://github.com/nodejs/node/pull/7552](https://github.com/nodejs/node/pull/7552). As of node 7.4 there's experimental `domainToASCII` and `domainToUnicode` functions in the [url](https://nodejs.org/api/url.html#url_url_domaintoascii_domain) module. So perhaps in node v8+, we'll no longer use the punycode module at all (see that conversation in 7522 thread). In the meantime, an explicit declaration will work.

**Comment by baudehlo** [comment]
I'm having trouble publishing this - it seems to be published by "haraka" but not one of @haraka the group's npm modules: https://www.npmjs.com/org/haraka

Do we need to email npm support?

**Comment by msimerson** [comment]
Unfortunately, @haraka doesn't work the way you'd expect on NPM. I just manually added your and Steve's npm ids to this module.

**Comment by msimerson** [comment]
I think you'd be able to had you tried again but I just published this.

````
$ npm publish
+ address-rfc2821@1.1.0
````

**Pull request merged**
